#!/bin/bash  -x
module="scull"
device="scull"

rm -f /dev/${device}[0-3]
lsmod |grep $module || insmod ./$module.ko $* || exit 1

major=$(awk "/$device/{print \$1}" /proc/devices)
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3

group="staff"

grep "^staff" /etc/group || group="wheel"
chgrp $group /dev/${device}[0-3]

mode=664
chmod $mode /dev/${device}[0-3]
