//
// Created by cathy on 17-5-14.
//

#ifndef SCULL_ZXL_SCULL_H
#define SCULL_ZXL_SCULL_H

#endif //SCULL_ZXL_SCULL_H

#define SCULL_IOC_MAGIC 'x'

#define SCULL_IOCRESET _IO(SCULL_IOC_MAGIC, 0)
#define SCULL_IOCTQSET _IO(SCULL_IOC_MAGIC, 1)
#define SCULL_IOCTQUANTUM _IO(SCULL_IOC_MAGIC, 2)
#define SCULL_IOCSQSET _IOW(SCULL_IOC_MAGIC, 3, int)
#define SCULL_IOCSQUANTUM _IOW(SCULL_IOC_MAGIC, 4, int)
#define SCULL_IOCQQSET _IO(SCULL_IOC_MAGIC, 5)
#define SCULL_IOCQQUANTUM _IO(SCULL_IOC_MAGIC, 6)
#define SCULL_IOCGQSET _IOR(SCULL_IOC_MAGIC, 7, int)
#define SCULL_IOCGQUANTUM _IOR(SCULL_IOC_MAGIC, 8, int)
#define SCULL_IOCHQSET _IO(SCULL_IOC_MAGIC, 9)
#define SCULL_IOCHQUANTUM _IO(SCULL_IOC_MAGIC, 10)
#define SCULL_IOCXQSET _IOWR(SCULL_IOC_MAGIC, 11, int)
#define SCULL_IOCXQUANTUM _IOWR(SCULL_IOC_MAGIC, 12, int)

#define SCULL_IOC_MAXNUM 13

#define SCULL_QSET 10
#define SCULL_QUANTUM 500